baseDjangoProject/baseDjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls, name='admin'),
]

baseDjangoProject/mainapp/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'mainapp'

urlpatterns = [
  path('', views.index, name='index'),
  path('login/', views.login_request, name='login'),
  path("logout/", views.logout_request, name="logout"),
  path("profile/", views.profile, name="profile"),
  path('register/', views.register_request, name='register'),
]

baseDjangoProject/mainapp/models.py
from django.db import models

# Create your models here.

baseDjangoProject/mainapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    password1 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

baseDjangoProject/mainapp/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from .forms import NewUserForm

def index(request):
  return render(request, 'mainapp/index.html')

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}")
				return redirect('mainapp:profile')
			else:
				messages.error(request,"Invalid username or password")
		else:
			messages.error(request,"Invalid username or password")
	form = AuthenticationForm()
	return render(request=request, template_name="mainapp/login.html", context={"login_form":form})

def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out") 
	return redirect('mainapp:index')

def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful" )
			return redirect('mainapp:index')
		messages.error(request, "Unsuccessful registration : invalid information")
	form = NewUserForm()
	return render(request=request, template_name="mainapp/register.html", context={"register_form":form})

def profile(request):
    return render(request=request, template_name="mainapp/profile.html")

baseDjangoProject/mainapp/templates/mainapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'mainapp/index.css' %}">
    <title>baseDjangoProject</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'mainapp:index' %}">Home</a></li>
            {% if user.is_authenticated %}
                <a href="{% url 'mainapp:profile' %}">{{ user.get_username }}</a>
            {% else %}
                <li><a href="{% url 'mainapp:login' %}">Log in</a></li>
                <li><a href="{% url 'mainapp:register' %}">Register</a></li>
            {% endif %}
        </ul>
    </nav>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="content">
        <h1>baseDjangoProject</h1>
        <h3>Base main-app Django project to start coding directly.</h3>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

baseDjangoProject/mainapp/templates/mainapp/login.html
{% extends 'mainapp/index.html' %}

{% block content %}
    <style>
        form {
            display: flex;
            text-align: center;
            flex-direction: column;
            padding: 30px 30px 25px 30px;
            background-color: #101122;
            border-radius: 20px;
            box-shadow: 0px 5px 20px rgba(0, 0, 0, 0.1);
            margin: 25px;
        }

        input[type="text"], input[type="password"] {
            background-color: #241579;
            border: 0px solid #ffffff;
            color: #ffffff;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 16px;
            padding: 15px 20px;
            margin-bottom: 20px;
            width: 100%;
        }

        button[type="submit"] {
            background-color: #87abe4;
            border: none;
            color: #fff;
            cursor: pointer;
            font-size: 16px;
            font-weight: bold;
            margin-top: 5px;
            padding: 15px 20px;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        button[type="submit"]:hover {
            background-color: #241579;
        }

        form a {
            color: #ffffff;
            text-decoration: none;
            font-size: 14px;
            margin-top: 10px;
            text-align: center;
        }
    </style>
    <form method="post">
        {% csrf_token %}
        <input type="text" id="username" name="username" placeholder="Username" required>
        <input type="password" id="password" name="password" placeholder="Password" required>
        <button type="submit">Login</button>
        <a href="{% url 'mainapp:register' %}">Register instead</a>
    </form>
{% endblock %}

baseDjangoProject/mainapp/templates/mainapp/profile.html
{% extends 'mainapp/index.html' %}

{% block content %}
    <style>
        form {
            display: flex;
            text-align: center;
            flex-direction: column;
            padding: 20px 30px 25px 30px;
            background-color: #101122;
            border-radius: 20px;
            box-shadow: 0px 5px 20px rgba(0, 0, 0, 0.1);
            margin: 25px;
        }

        button[type="submit"] {
            background-color: #87abe4;
            border: none;
            color: #fff;
            cursor: pointer;
            font-size: 16px;
            font-weight: bold;
            margin-top: 5px;
            padding: 15px 20px;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        button[type="submit"]:hover {
            background-color: #241579;
        }

        form a {
            color: #ffffff;
            text-decoration: none;
            font-size: 14px;
            margin-top: 10px;
            text-align: center;
        }
    </style>
    <form method="POST" action="{% url 'mainapp:logout' %}">
        {% csrf_token %}
        <button type="submit">Log out</button>
    </form>
    {% if user.is_superuser %}
        <a href="{% url 'admin:index' %}">Admin panel</a>
    {% endif %}
{% endblock %}

baseDjangoProject/mainapp/templates/mainapp/register.html
{% extends 'mainapp/index.html' %}

{% block content %}
    <style>
        form {
            display: flex;
            text-align: center;
            flex-direction: column;
            padding: 30px 30px 25px 30px;
            background-color: #101122;
            border-radius: 20px;
            box-shadow: 0px 5px 20px rgba(0, 0, 0, 0.1);
            margin: 25px;
        }

        input[type="text"], input[type="password"] {
            background-color: #241579;
            border: 0px solid #ffffff;
            color: #ffffff;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 16px;
            padding: 15px 20px;
            margin-bottom: 20px;
            width: 100%;
        }

        button[type="submit"] {
            background-color: #87abe4;
            border: none;
            color: #fff;
            cursor: pointer;
            font-size: 16px;
            font-weight: bold;
            margin-top: 5px;
            padding: 15px 20px;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        button[type="submit"]:hover {
            background-color: #241579;
        }

        form a {
            color: #ffffff;
            text-decoration: none;
            font-size: 14px;
            margin-top: 10px;
            text-align: center;
        }
    </style>
    <form method="POST">
	    {% csrf_token %}
	    <div>
            {{ register_form.username }}
        </div>
        <div>
            {{ register_form.email }}
        </div>
        <div>
            {{ register_form.password1 }}
        </div>
        <div>
            {{ register_form.password2 }}
        </div> 
		<button type="submit">Register</button>
        <a href="{% url 'mainapp:login' %}">Log in instead</a>
	</form>
{% endblock %}